apiVersion: v2
name: otp-inbox
description: A private inbox for SMS, email, and Bitwarden verification codes
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/pmh-only/otp
sources:
  - https://github.com/pmh-only/otp
