{{- if .Values.sealedSecret.enabled }}
{{- if .Values.secrets.existingSecret }}
{{- fail "secrets.existingSecret and sealedSecret.enabled cannot both be set" }}
{{- end }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "otp.fullname" . }}
  labels:
    {{- include "otp.labels" . | nindent 4 }}
  {{- with .Values.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    CONNECT_ROSTACK_TOKEN: {{ required "sealedSecret.encryptedData.CONNECT_ROSTACK_TOKEN is required" (index .Values.sealedSecret.encryptedData "CONNECT_ROSTACK_TOKEN") | quote }}
    MAIL_ROSTACK_TOKEN: {{ required "sealedSecret.encryptedData.MAIL_ROSTACK_TOKEN is required" (index .Values.sealedSecret.encryptedData "MAIL_ROSTACK_TOKEN") | quote }}
    {{- with (index .Values.sealedSecret.encryptedData "BITWARDEN_API_TOKEN") }}
    BITWARDEN_API_TOKEN: {{ . | quote }}
    {{- end }}
    {{- if .Values.bitwarden.enabled }}
    BW_CLIENTID: {{ required "sealedSecret.encryptedData.BW_CLIENTID is required when bitwarden.enabled is true" (index .Values.sealedSecret.encryptedData "BW_CLIENTID") | quote }}
    BW_CLIENTSECRET: {{ required "sealedSecret.encryptedData.BW_CLIENTSECRET is required when bitwarden.enabled is true" (index .Values.sealedSecret.encryptedData "BW_CLIENTSECRET") | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "otp.fullname" . }}
      labels:
        {{- include "otp.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
